---
sidebar: sidebar 
permalink: oci/add-credentials-oci.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 'Workload Factory가 OCI 계정의 클라우드 리소스를 배포하고 관리하는 데 필요한 권한을 갖도록 Oracle Cloud Infrastructure(OCI) 자격 증명을 추가하십시오.' 
---
= NetApp Workload Factory에 Oracle Cloud Infrastructure 자격 증명을 추가합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory가 클라우드 공급자 계정의 리소스를 배포하고 관리하는 데 필요한 권한을 갖도록 클라우드 공급자 자격 증명을 추가하고 관리하십시오.

link:permissions-oci.html["OCI NetApp 스토리지 서비스에 대한 권한"]

.이 작업 정보
자격 증명 페이지에서 기존 Workload Factory 계정에 자격 증명을 추가할 수 있습니다. 이는 Workload Factory에 클라우드 환경 내의 리소스 및 프로세스를 관리하는 데 필요한 권한을 제공합니다.

.시작하기 전에
Oracle Cloud Infrastructure 계정에 로그인하려면 자격 증명이 필요합니다.

.단계
.  https://console.netapp.com/["NetApp 콘솔"^]에 로그인합니다.
. 메뉴에서 *워크로드* > *관리* > *자격 증명*을 선택하십시오.
. 자격 증명 페이지에서 *자격 증명 추가*를 선택합니다.
. Oracle Cloud Infrastructure NetApp 스토리지 서비스 자격 증명 추가 페이지에서 다음을 수행하십시오:
+
.. _권한 구성_에서 Oracle Cloud Infrastructure NetApp Storage Service 자격 증명에 적합한 권한을 선택하십시오. *보기, 계획 및 분석* 권한이 기본값입니다. 이 권한 정책을 사용하면 OCI NSS 스토리지 풀을 보고, 시스템 상태를 확인하고, 시스템에 대한 아키텍처 분석을 수행하고, 비용 절감 방안을 살펴볼 수 있습니다.
.. Oracle Cloud Console을 사용하여 제공된 수동 단계를 따라 OCI NSS 자격 증명에 대한 권한 구성을 완료하십시오.
.. _자격 증명 이름_ 아래에 이 자격 증명에 사용할 이름을 입력하고 테넌시 OCID를 입력합니다.


. *추가*를 선택합니다.


.다음 단계
link:quick-start-oci.html["NetApp Workload Factory에서 Oracle Cloud Infrastructure NetApp 스토리지 서비스를 빠르게 시작하는 방법입니다."]
