---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원되지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 
---
= NetApp Workload Factory의 FSx for ONTAP 워크로드에 대한 알려진 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원되지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 다음 제한 사항은 NetApp Workload Factory의 Amazon FSx for NetApp ONTAP에만 해당됩니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



[[known-limitations-of-fsx-for-ontap-storage-workloads]]
== FSx for ONTAP 스토리지 워크로드의 알려진 제한 사항



[[region-support]]
=== 지역 지원

다음 AWS 리전은 지원되지 않습니다.

* 중국 지역
* Secret Cloud
* 최고 기밀 클라우드




[[adding-ha-pairs-limitations]]
=== HA 쌍 추가 제한 사항

* 이 작업은 완료하는 데 약 30분이 소요될 수 있습니다.
* HA 쌍을 추가하면 다음과 같은 작업이 제한됩니다: HA 쌍 추가, IOPS 프로비저닝, SSD 용량 증가 및 처리량 용량 업데이트.




[[throughput-capacity-region-support]]
=== 처리량 용량 리전 지원



==== 스케일업 배포

모든 지역에서 스케일업 구성은 최대 2GB/s까지 지원됩니다. 다음 지역에서는 스케일업 배포 시 최대 4GB/s의 처리량 용량을 지원합니다. 미국 동부(오하이오) 지역, 미국 동부(버지니아 북부) 지역, 미국 서부(오리건) 지역 및 유럽(아일랜드).



==== 스케일아웃 배포

다음 지역은 스케일아웃 배포를 위해 최대 6GB/s의 최대 처리량 용량을 지원합니다: 미국 동부(버지니아 북부 및 오하이오), 미국 서부(캘리포니아 북부 및 오리건), 유럽(프랑크푸르트, 아일랜드 및 스톡홀름), 아시아 태평양(싱가포르 및 시드니).



[[capacity-management]]
=== 용량 관리

* 현재 iSCSI 프로토콜에서는 볼륨 자동 확장 기능이 지원되지 않습니다.
* 자동 용량 관리 기능이 실행 중일 때는 수동으로 용량을 늘릴 수 없습니다.
* 자동 용량 관리 기능을 비활성화하려면 해당 기능을 활성화할 때 사용한 것과 동일한 권한이 필요합니다.
* 자동 용량 관리가 활성화된 경우, 볼륨 inode가 스토리지 용량과 함께 증가하도록 하려면 링크가 필요합니다.




[[storage-vms]]
=== 스토리지 VM

스토리지 VM의 수는 SKU별로 제한되어 있습니다. Workload Factory에서는 이 제한을 초과하는 스토리지 VM 생성을 지원하지 않습니다.^1^

파일 시스템당 최대 SVM 개수는 AWS 설명서의 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["FSx for ONTAP 스토리지 가상 머신 관리"^]을(를) 참조하십시오.



[[iscsi-protocol-support]]
=== iSCSI 프로토콜 지원

* iSCSI 프로토콜은 FlexVol 볼륨에서만 사용할 수 있습니다. ^1^
* iSCSI 볼륨의 경우 볼륨 크기 축소가 지원되지 않습니다.




[[data-protection]]
=== 데이터 보호

* 스냅샷은 삭제할 수 없습니다.
* 파일 시스템을 복제하면 파일 시스템의 모든 볼륨이 동일한 복제 정책을 사용합니다.
* 장기 보존 복제 관계의 경우, 복원에는 마지막 스냅샷만 사용할 수 있습니다.
* 불변 스냅샷에서는 다음과 같은 기능이 지원되지 않습니다:
+
** 일관성 그룹
** FabricPool
** FlexCache 볼륨
** SMtape
** SnapMirror 액티브 동기화
** -schedule 매개변수를 사용하는 SnapMirror 정책 규칙
** SnapMirror 동기식
** SVM 데이터 이동성(소스 클러스터에서 타겟 클러스터로 SVM을 마이그레이션하거나 재배치하는 데 사용됨)






[[storage-savings-calculator]]
=== 스토리지 절감 계산기

스토리지 비용 절감 계산기는 다음 구성에 대한 비용 절감액을 계산하지 않습니다:

* FSx for Windows File Server: HDD 스토리지 유형
* Elastic Block Store(EBS): st1, sc1 및 표준 볼륨 유형
* Elastic File System (EFS): 버스팅 처리량 모드




[[aws-secrets-manager-support]]
=== AWS Secrets Manager 지원

콘솔 에이전트를 사용할 때는 AWS Secrets Manager가 지원되지 않습니다.



[[amazon-s3-access-points-limitation]]
=== Amazon S3 액세스 포인트 제한

스토리지 VM당 S3 액세스 포인트 수의 제한은 4,000개입니다.



[[limitations-for-storage-vm-migration-replication]]
=== 스토리지 VM 마이그레이션 복제 제한 사항

* Workload Factory는 1세대와 2세대 FSx for ONTAP 파일 시스템 간의 스토리지 VM 마이그레이션 복제를 지원하지 않습니다.
* S3 액세스 포인트 또는 vserver의 object-store-server, 버킷, 사용자, 그룹 또는 정책을 포함하는 ONTAP S3 구성이 있는 볼륨의 경우 컷오버 복제가 지원되지 않습니다.


참고:

. Amazon FSx for NetApp ONTAP에 적용됩니다




[[known-limitations-of-fsx-for-ontap-database-workloads]]
== FSx for ONTAP 데이터베이스 워크로드의 알려진 제한 사항



[[instance-detection-support]]
=== 인스턴스 감지 지원

Workload Factory는 Amazon Linux 운영 체제에서만 실행되는 PostgreSQL 인스턴스와 Red Hat Enterprise Linux에서만 실행되는 Oracle 인스턴스를 감지하는 기능을 지원합니다.



[[ami-image-version-support]]
=== AMI 이미지 버전 지원

각 SQL 버전별로 최대 4개의 최신 버전 또는 리비전의 AMI 이미지만 표시됩니다. 최신 4개 버전보다 오래된 AMI 이미지를 사용한 설치는 허용되지 않습니다.



[[custom-ami]]
=== 사용자 지정 AMI

사용자 지정 AMI를 사용한 배포는 이미지에 설치 미디어가 포함되어 있다고 가정합니다. 이는 다음과 같은 이유로 FCI 구성에 필요합니다:

* FCI 클러스터를 구성하기 위해 제거 및 재구성하려면
* 독립 실행형 배포용 이미지에 설정된 정렬 방식과 다른 정렬 방식을 선택할 경우


Workload Factory는 배포 과정에서 여러 Microsoft SQL Server 인스턴스가 포함된 사용자 지정 AMI를 설치하지 않습니다. 배포 시에는 기본 Microsoft SQL Server 인스턴스만 선택 및 구성됩니다.



[[roll-back-and-retry-for-failed-deployments]]
=== 배포 실패 시 롤백 및 재시도

Workload Factory에서는 배포 실패에 대한 롤백 및 재시도가 지원되지 않습니다. AWS의 CloudFormation 콘솔에서 실패한 스택을 롤백하거나 재시도할 수 있습니다.



[[active-directory-and-dns-resource-rollback]]
=== Active Directory 및 DNS 리소스 롤백

AWS의 CloudFormation 콘솔에서 테스트 또는 실패한 배포를 롤백할 때 다음 DNS 리소스는 Active Directory 및 DNS에서 제거되지 않습니다:

* SQL 배포의 각 노드에서 해당 관리 IP 주소로
* FCI의 경우 EC2 인스턴스의 예약된 보조 IP 주소에 Windows 클러스터 이름 지정
* SQL FCI 이름을 FCI의 두 EC2 인스턴스에서 예약된 두 개의 IP 주소에 연결합니다.


이러한 항목은 수동으로 정리하거나 도메인에서 오래된 항목을 제거할 때까지 기다려야 합니다.



[[always-on-availability-groups-configuration-support]]
=== Always On 가용성 그룹 구성 지원

Workload Factory에서는 Always On 가용성 그룹 구성 관리가 지원되지 않습니다.



[[custom-encryption-keys]]
=== 사용자 지정 암호화 키

FSx for ONTAP용 사용자 지정 암호화 키는 서비스 적용 가능성에 따라 나열되지 않습니다. 적절한 키를 선택해야 합니다. AWS 관리형 키는 서비스 적용 가능성에 따라 필터링됩니다.



[[cloudformation-template]]
=== CloudFormation 템플릿

다운로드하거나 복사한 Codebox 생성 CloudFormation 템플릿(YAML 파일)의 보존 기간은 7일로 제한됩니다.



[[sandbox-support]]
=== 샌드박스 지원

데이터베이스 서버에서 생성할 수 있는 샌드박스 클론의 최대 개수는 90개입니다.



[[microsoft-sql-server-detection-and-management]]
=== Microsoft SQL Server 감지 및 관리

Microsoft SQL Server 감지 정보는 저장되지 않습니다. Workload Factory에서 데이터베이스에 액세스할 때마다 Microsoft SQL Server 감지가 다시 실행되어 해당 지역의 SQL 설치를 식별합니다.



[[explore-savings]]
=== 할인 혜택을 살펴보세요

인벤토리 탭에서 각 Microsoft SQL 인스턴스에 대해 표시되는 예상 비용은 SQL 인스턴스를 호스팅하는 볼륨이 아닌 FSx for ONTAP 파일 시스템 수준에서 계산됩니다.



[[multiple-fsx-for-ontap-file-systems]]
=== 다중 FSx for ONTAP 파일 시스템

Workload Factory는 여러 개의 FSx for ONTAP 파일 시스템을 사용하는 Microsoft SQL Server 구성 생성 또는 저장을 지원하지 않습니다. 하나의 FSx for ONTAP 파일 시스템 구성 배포만 지원됩니다.



[[optimization-limitations]]
=== 최적화 제한 사항



==== 컴퓨팅 적정 규모 산정 최적화

특정 인스턴스 유형으로 변경할 때 네트워크 구성이 재설정될 수 있으며, 이로 인해 최적화 중에 노드 연결 오류가 발생하여 작업이 실패할 수 있습니다. DNS 설정 및 iSCSI 세션을 확인하고 업데이트하려면 수동 작업이 필요할 수 있습니다. EC2 크기 조정 제한에 대한 자세한 내용은 link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Amazon Elastic Compute Cloud 설명서"^]을(를) 참조하십시오.



==== ONTAP 및 OS 구성 최적화

ONTAP 구성 및 OS 구성에 대해서는 둘 이상의 SQL Server 인스턴스에 대한 일괄 최적화가 지원되지 않습니다.



==== 최적화를 위한 운영 체제 패치 평가

최적화 목적으로 수행되는 운영 체제 패치 평가는 프라이빗 네트워크에서 작동하지 않을 수 있습니다. 이 평가는 AWS Patch Manager에 의존합니다. 프라이빗 네트워크에서 Windows EC2 인스턴스에 패치를 적용하는 방법을 알아보려면 AWS Cloud Operations Blog link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["AWS Systems Manager를 사용하여 프라이빗 서브넷의 Windows EC2 인스턴스에 패치를 적용하는 방법"^]를 참조하십시오.



==== 지역 간 복제 평가

* 최적화 평가에서는 대상 FSx for ONTAP 파일 시스템이 다른 AWS 계정에 있는 경우 교차 리전 복제(CRR)가 사용되고 있는지 여부를 확인할 수 없습니다.
* Workload Factory는 소스 FSx for ONTAP 파일 시스템의 CRR 구성만 평가합니다.




[[on-premises-savings-calculation]]
=== 온프레미스 절감액 계산

Microsoft SQL Server 온프레미스 스토리지의 볼륨 크기에 대한 비용 및 절감률 계산은 고려되지 않습니다.



[[database-host-authentication-when-exploring-savings]]
=== 절약 효과를 탐색할 때 데이터베이스 호스트 인증

권한이 제한된 일부 경우, 인증에 성공한 후에도 절감액 탐색 페이지에서 데이터를 로드하지 않습니다.



[[integration-with-netapp-backup-and-recovery]]
=== NetApp Backup and Recovery와의 통합

보호를 위해 호스트를 NetApp Backup and Recovery에 추가한 후 데이터베이스 검색이 실패하는 경우가 있습니다.



[[registering-oracle-on-suse-linux-enterprise-server-12]]
=== SUSE Linux Enterprise Server 12에 Oracle 등록하기

SUSE Linux Enterprise Server 12에 Oracle Database를 등록할 때 Workload Factory는 Python 종속성을 설치하지 않습니다. 필요한 Python 버전을 수동으로 구성해야 합니다. Workload Factory는 최소 3.6 버전을 요구하지만, 3.11 버전을 권장합니다.



[[known-limitations-for-eda-workloads]]
== EDA 워크로드의 알려진 제한 사항



[[operator-permissions-required]]
=== 운영자 권한이 필요합니다

NetApp Workload Factory for EDA가 정상적으로 작동하려면 운영자 권한이 필요합니다.
