---
sidebar: sidebar 
permalink: fsx-storage/create-discover-systems.html 
keywords: Amazon FSx for NetApp ONTAP, fsx, volumes, create system, delete system, access key, secret key, region, availability zones, discover, storage capacity, iops, throughput, security group, security, NetApp Console 
summary: NetApp Console에서 클라우드 스토리지 시스템을 생성하거나 검색하여 볼륨 및 추가 데이터 서비스를 추가하고 관리할 수 있습니다. 
---
= NetApp Console에서 클라우드 스토리지 시스템을 생성하거나 검색합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Console에서 클라우드 스토리지 시스템을 생성하거나 검색하여 볼륨 및 추가 데이터 서비스를 추가하고 관리할 수 있습니다.



[[create-a-storage-system]]
== 스토리지 시스템 생성

첫 번째 단계는 스토리지 시스템을 생성하는 것입니다. 클라우드 제공업체의 콘솔에서 이미 스토리지 시스템을 생성한 경우 <<기존 클라우드 스토리지 시스템 검색,NetApp Console을 사용하여 검색하십시오>> 할 수 있습니다.

.이 작업 정보
파일 시스템을 생성할 때 스토리지 VM이 생성됩니다.

.시작하기 전에
FSx for ONTAP 파일 시스템을 생성하기 전에 다음이 필요합니다.

* Workload Factory에 FSx for ONTAP 파일 시스템을 생성하는 데 필요한 권한을 부여하는 IAM 역할의 ARN입니다. link:permissions-reference-fsx.html["AWS 계정에 권한을 부여하는 방법을 알아보십시오"^].
* FSx for ONTAP 인스턴스를 생성할 리전 및 VPC 정보입니다.




[[create-an-fsx-for-ontap-file-system]]
== FSx for ONTAP 파일 시스템을 생성합니다.

_빠른 생성_ 또는 _고급 생성_을 사용하여 FSx for ONTAP 파일 시스템을 생성할 수 있습니다. 또한 Codebox에서 제공되는 REST API, CloudFormation 및 Terraform 툴을 사용할 수도 있습니다. link:../admin/use-codebox.html#how-to-use-codebox["Codebox를 활용한 자동화 방법을 알아보세요"^].


NOTE: Codebox에서 Terraform을 사용할 경우, 복사하거나 다운로드하는 코드에는  `fsxadmin` 및  `vsadmin` 암호가 숨겨져 있습니다. 코드를 실행할 때 암호를 다시 입력해야 합니다.

[role="tabbed-block"]
====
.빠른 생성
--
빠른 생성 기능을 사용하면 권장 모범 사례 구성을 사용할 수 있습니다. FSx for ONTAP 파일 시스템을 생성한 후 대부분의 설정을 변경할 수 있습니다.

.단계
. NetApp Console 메뉴에서 *스토리지*를 선택한 다음 *관리*를 선택합니다.
. 시스템 페이지에서 *시스템 추가*를 선택하세요.
. 위치로 *Amazon Web Services*를 선택한 다음 Amazon FSx for NetApp ONTAP에 대해 *새로 추가*를 선택합니다.
. FSx for ONTAP 파일 시스템 생성 페이지에서 *빠른 생성*을 선택합니다.
+
저장된 구성을 로드할 수도 있습니다.

. 파일 시스템 일반 구성에서 다음을 제공하십시오:
+
.. *AWS 자격 증명*: Workload Factory에 AWS 자격 증명을 추가하거나 자격 증명 없이 계속 진행하려면 선택하십시오.
.. *파일 시스템 이름*: 파일 시스템의 이름을 입력하십시오.
.. *지역 및 VPC*: 파일 시스템에 사용할 지역과 VPC를 선택하십시오.
.. *배포 유형*: 배포 유형을 선택하십시오.
+
*** 단일 가용 영역(Single-AZ) 배포: 하드웨어 오류를 모니터링하고 오류 발생 시 인프라 구성 요소를 자동으로 교체하여 가용성을 제공합니다. 가용 영역 내에서 데이터를 자동으로 복제하여 구성 요소 오류로부터 데이터를 보호함으로써 높은 내구성을 구현합니다.
+
이 구성은 고성능 워크로드 또는 워크로드가 소규모로 시작하여 점진적으로 72 GB/s의 처리량과 240만 IOPS까지 확장될 때 권장됩니다.

*** 다중 가용 영역(Multi-AZ) 배포: 가용 영역을 사용할 수 없는 경우에도 데이터에 대한 지속적인 가용성을 제공합니다. 다중 AZ 파일 시스템은 공유 ONTAP 파일 데이터에 대한 높은 가용성이 필요하고 가용 영역 간 복제 기능이 내장된 스토리지가 필요한 비즈니스 크리티컬 프로덕션 워크로드를 위해 설계되었습니다.
+
이 단일 HA 쌍 구성은 최대 6 GB/s의 처리량 또는 200,000 IOPS가 필요한 워크로드에 권장됩니다.



.. *태그*: 선택 사항으로 최대 50개의 태그를 추가할 수 있습니다.


. *파일 시스템 세부 정보*에 다음 정보를 입력하십시오.
+
.. *SSD 스토리지 용량*: 스토리지 용량을 입력하고 스토리지 용량 단위를 선택하십시오.
+
*** 1세대 배포의 경우 파일 시스템 생성 후에는 용량을 줄일 수 없습니다.
*** 2세대 배포의 경우 파일 시스템 생성 후 용량을 늘릴 수 있습니다.


.. *ONTAP 자격 증명*: 선택 사항입니다. ONTAP 사용자 이름과 비밀번호를 입력하십시오. 비밀번호는 지금 또는 나중에 설정할 수 있습니다.
+
제공한 사용자가 fsxadmin 사용자가 아니고 나중에 fsxadmin 암호를 재설정해야 하는 경우 AWS 콘솔에서 재설정할 수 있습니다.

.. *SMB/CIFS 설정*: 선택 사항입니다. SMB/CIFS 프로토콜을 사용하여 볼륨에 액세스하려면 파일 시스템 생성 중에 스토리지 VM에 대한 Active Directory를 구성해야 합니다. 이 파일 시스템에 대해 생성되는 스토리지 VM에 대해 다음 세부 정보를 제공하십시오.
+
... *가입할 Active Directory 도메인*: Active Directory의 정규화된 도메인 이름(FQDN)을 입력하십시오.
... *DNS IP 주소*: 쉼표로 구분하여 최대 3개의 DNS IP 주소를 입력하십시오.
... *SMB 서버 NetBIOS 이름*: 스토리지 VM용으로 생성할 Active Directory 컴퓨터 오브젝트의 SMB 서버 NetBIOS 이름을 입력하십시오. 이 이름은 Active Directory에서 해당 스토리지 VM의 이름입니다.
... *사용자 이름*: 기존 Active Directory에 있는 서비스 계정의 사용자 이름을 입력하십시오.
+
도메인 접두사나 접미사를 포함하지 마십시오.  `EXAMPLE\ADMIN`의 경우  `ADMIN`를 사용하십시오.

... *비밀번호*: 서비스 계정의 비밀번호를 입력하세요.
... *조직 단위*: 선택적으로, FSx for ONTAP용 컴퓨터 계정을 생성하려는 조직 단위의 이름을 입력합니다. OU는 파일 시스템을 연결하려는 조직 단위의 고유 경로 이름입니다.
... *위임된 관리자 그룹*: 선택적으로 파일 시스템을 관리할 수 있는 Active Directory 그룹의 이름을 입력합니다.
+
AWS Managed Microsoft AD를 사용하는 경우, AWS Delegated FSx Administrators, AWS Delegated Administrators 또는 OU에 대한 위임 권한이 있는 사용자 지정 그룹 등의 그룹을 지정해야 합니다.

+
자체 관리형 AD에 참여하는 경우 AD의 그룹 이름을 사용하십시오. 기본 그룹은  `Domain Admins`입니다.





. *요약*을 열어 정의한 구성을 검토하십시오. 필요한 경우, 파일 시스템을 저장하거나 생성하기 전에 설정을 변경할 수 있습니다.
. 파일 시스템을 저장하거나 생성합니다.


.결과
파일 시스템을 생성한 경우, 새로운 FSx for ONTAP 구성이 시스템 페이지에 나타납니다.

FSx for ONTAP 파일 시스템은 NetApp Console의 워크로드, ONTAP 시스템 관리자, AWS CloudFormation을 사용하는 등 여러 가지 방법으로 관리할 수 있습니다.

--
.고급 생성
--
고급 생성을 사용하면 가용성, 보안, 백업, 유지 관리 등 모든 구성 옵션을 설정할 수 있습니다.

.단계
. NetApp Console 메뉴에서 *스토리지*를 선택한 다음 *관리*를 선택합니다.
. 시스템 페이지에서 *시스템 추가*를 선택하세요.
. 위치로 *Amazon Web Services*를 선택한 다음 Amazon FSx for NetApp ONTAP에 대해 *새로 추가*를 선택합니다.
. ONTAP 파일 시스템용 FSx 생성 페이지에서 *고급 생성*을 선택합니다.
+
저장된 구성을 로드할 수도 있습니다.

. 파일 시스템 일반 구성에서 다음을 제공하십시오:
+
.. *AWS 자격 증명*: Workload Factory에 AWS 자격 증명을 추가하거나 자격 증명 없이 계속 진행하려면 선택하십시오.
.. *파일 시스템 이름*: 파일 시스템의 이름을 입력하십시오.
.. *지역 및 VPC*: 파일 시스템에 사용할 지역과 VPC를 선택하십시오.
.. *배포 유형*: 배포 유형과 파일 시스템 세대를 선택하십시오. 2세대 파일 시스템의 사용 가능 여부는 선택한 지역에 따라 다릅니다. 선택한 지역에서 ONTAP 파일 시스템용 2세대 FSx를 지원하지 않는 경우 배포 유형은 1세대로 전환됩니다.
+
*** 단일 가용 영역(Single-AZ) 배포: 하드웨어 오류를 모니터링하고 오류 발생 시 인프라 구성 요소를 자동으로 교체하여 가용성을 제공합니다. 가용 영역 내에서 데이터를 자동으로 복제하여 구성 요소 오류로부터 데이터를 보호함으로써 높은 내구성을 구현합니다.
+
*파일 시스템 생성*: 다음 중 하나를 선택하십시오:

+
**** *2세대*: 이 구성은 고성능 워크로드 또는 워크로드가 소규모로 시작하여 점진적으로 72GB/s의 처리량과 240만 IOPS까지 확장될 때 권장됩니다.
**** *1세대*: 이 구성은 최대 4GB/s 또는 160,000 IOPS가 필요한 워크로드에 적합합니다. 1세대 파일 시스템은 용량만 증가시킬 수 있습니다.


*** 다중 가용 영역(Multi-AZ) 배포: 가용 영역을 사용할 수 없는 경우에도 데이터에 대한 지속적인 가용성을 제공합니다. 다중 AZ 파일 시스템은 공유 ONTAP 파일 데이터에 대한 높은 가용성이 필요하고 가용 영역 간 복제 기능이 내장된 스토리지가 필요한 비즈니스 크리티컬 프로덕션 워크로드를 위해 설계되었습니다.
+
*파일 시스템 생성*: 다음 중 하나를 선택하십시오:

+
**** *2세대*: 이 단일 HA 쌍 구성은 최대 6GB/s의 처리량 또는 200,000 IOPS가 필요한 워크로드에 권장됩니다. 멀티 AZ 및 2세대 파일 시스템에서는 워크로드 요구 사항에 맞춰 용량을 늘리거나 줄일 수 있습니다.
**** *1세대*: 이 구성은 최대 4GB/s 또는 160,000 IOPS가 필요한 워크로드에 적합합니다. 1세대 파일 시스템은 용량만 증가시킬 수 있습니다.




.. *태그*: 선택 사항으로 최대 50개의 태그를 추가할 수 있습니다.


. 파일 시스템 세부 정보란에 다음 정보를 입력하십시오.
+
.. *SSD 스토리지 용량*: 스토리지 용량을 입력하고 스토리지 용량 단위를 선택하십시오.
+
*** 1세대 배포의 경우 파일 시스템 생성 후에는 용량을 줄일 수 없습니다.
*** 2세대 구축의 경우 용량을 조정할 수 있습니다.


.. *HA 쌍당 처리량 용량*: HA 쌍 개수당 처리량 용량을 선택하십시오. 1세대 파일 시스템은 하나의 HA 쌍만 지원합니다.
.. *프로비저닝된 IOPS*: 다음 옵션 중 하나를 선택하십시오:
+
*** *자동*: 자동 모드의 경우, 생성되는 1GiB당 3 IOPS가 추가됩니다.
*** *사용자 프로비저닝*: 사용자 프로비저닝의 경우 IOPS 값을 입력하십시오.


.. *ONTAP 자격 증명*: 선택 사항입니다. ONTAP 사용자 이름과 비밀번호를 입력하십시오. 비밀번호는 지금 또는 나중에 설정할 수 있습니다.
+
제공한 사용자가 fsxadmin 사용자가 아니고 나중에 fsxadmin 암호를 재설정해야 하는 경우 AWS 콘솔에서 재설정할 수 있습니다.

.. *스토리지 VM 자격 증명*: 선택 사항입니다. 사용자 이름을 입력하십시오. 암호는 이 파일 시스템에 특화된 암호를 사용하거나 ONTAP 자격 증명에 입력한 암호를 사용할 수 있습니다. 암호는 지금 또는 나중에 설정할 수 있습니다.
.. *SMB/CIFS 설정*: 선택 사항입니다. SMB/CIFS 프로토콜을 사용하여 볼륨에 액세스하려면 파일 시스템 생성 중에 스토리지 VM에 대한 Active Directory를 구성해야 합니다. 이 파일 시스템에 대해 생성되는 스토리지 VM에 대해 다음 세부 정보를 제공하십시오.
+
... *가입할 Active Directory 도메인*: Active Directory의 정규화된 도메인 이름(FQDN)을 입력하십시오.
... *DNS IP 주소*: 쉼표로 구분하여 최대 3개의 DNS IP 주소를 입력하십시오.
... *SMB 서버 NetBIOS 이름*: 스토리지 VM용으로 생성할 Active Directory 컴퓨터 오브젝트의 SMB 서버 NetBIOS 이름을 입력하십시오. 이 이름은 Active Directory에서 해당 스토리지 VM의 이름입니다.
... *사용자 이름*: 기존 Active Directory에 있는 서비스 계정의 사용자 이름을 입력하십시오.
+
도메인 접두사나 접미사를 포함하지 마십시오.  `EXAMPLE\ADMIN`의 경우  `ADMIN`를 사용하십시오.

... *비밀번호*: 서비스 계정의 비밀번호를 입력하세요.
... *조직 단위*: 선택적으로, FSx for ONTAP용 컴퓨터 계정을 생성하려는 조직 단위의 이름을 입력합니다. OU는 파일 시스템을 연결하려는 조직 단위의 고유 경로 이름입니다.
... *위임된 관리자 그룹*: 선택적으로 파일 시스템을 관리할 수 있는 Active Directory 그룹의 이름을 입력합니다.
+
AWS Managed Microsoft AD를 사용하는 경우, AWS Delegated FSx Administrators, AWS Delegated Administrators 또는 OU에 대한 위임 권한이 있는 사용자 지정 그룹 등의 그룹을 지정해야 합니다.

+
자체 관리형 AD에 참여하는 경우 AD의 그룹 이름을 사용하십시오. 기본 그룹은  `Domain Admins`입니다.





. 네트워크 및 보안 항목에 다음 정보를 제공하십시오:
+
.. *보안 그룹*: 보안 그룹을 생성하거나 기존 보안 그룹을 사용합니다.
+
새 보안 그룹의 경우 보안 그룹 프로토콜, 포트 및 역할에 대한 설명은 <<Security group details,보안 그룹 세부 정보>>을(를) 참조하십시오.

.. *가용 영역*: 가용 영역 및 서브넷을 선택합니다.
+
*** 클러스터 구성 노드 1의 경우: 가용성 영역과 서브넷을 선택하십시오.
*** 클러스터 구성 노드 2의 경우: 가용성 영역과 서브넷을 선택하십시오.


.. *VPC 라우팅 테이블*: 클라이언트가 볼륨에 액세스할 수 있도록 VPC 라우팅 테이블을 선택하십시오.
.. *엔드포인트 IP 주소 범위*: *VPC 외부의 플로팅 IP 주소 범위* 또는 *IP 주소 범위 입력*을 선택하고 IP 주소 범위를 입력하십시오.
.. *암호화*: 드롭다운에서 암호화 키 이름을 선택하십시오.


. 백업 및 유지 관리 항목에 다음 정보를 제공하십시오.
+
.. *볼륨 백업*: 매일 자동 백업이 기본적으로 활성화되어 있습니다. 원하는 경우 비활성화합니다.
+
... *자동 백업 보존 기간*: 자동 백업을 보존할 일수를 입력하십시오.
... *일일 자동 백업 윈도우*: *설정 없음*(일일 백업 시작 시간이 자동으로 선택됨) 또는 *일일 백업 시작 시간 선택* 중 하나를 선택하고 시작 시간을 지정하십시오.


.. *주간 유지보수 윈도우*: *설정 없음*(주간 유지보수 윈도우 시작 시간이 자동으로 선택됨) 또는 *30분 주간 유지보수 윈도우 시작 시간 선택* 중 하나를 선택하고 시작 시간을 지정하십시오.


. 파일 시스템을 저장하거나 생성합니다.


.결과
파일 시스템을 생성한 경우, 새로운 FSx for ONTAP 구성이 시스템 페이지에 나타납니다.

FSx for ONTAP 파일 시스템은 NetApp Console의 워크로드, ONTAP 시스템 관리자, AWS CloudFormation을 사용하는 등 여러 가지 방법으로 관리할 수 있습니다.

--
====


[[discover-an-existing-cloud-storage-system]]
== 기존 클라우드 스토리지 시스템 검색

이전에 Workload Factory에 클라우드 스토리지 제공업체의 자격 증명을 입력한 경우, Discoverable systems 페이지에서 스토리지 시스템을 자동으로 검색할 수 있습니다. 또한 사용 가능한 데이터 서비스를 검토할 수도 있습니다.

.이 작업 정보
계정 내에서 클라우드 스토리지 시스템을 한 번만 검색하여 하나의 워크스페이스에 연결할 수 있습니다. 스토리지 시스템은 나중에 제거하고 다른 워크스페이스에 다시 연결할 수 있습니다.

.단계
. NetApp Console 메뉴에서 *스토리지*, *관리*, 그리고 *Discoverable systems*를 차례로 선택합니다.
. 검색된 클라우드 스토리지 시스템의 개수가 표시됩니다. *검색*을 선택합니다.
. 하나 이상의 스토리지 시스템을 선택하고 *검색*을 선택하여 시스템 페이지에 추가하십시오.


[NOTE]
====
* 이름이 지정되지 않은 스토리지 시스템을 선택하면 시스템 이름을 입력하라는 메시지가 표시됩니다.
* 콘솔에서 관리하는 데 필요한 자격 증명이 없는 스토리지 시스템을 선택하면 필요한 권한이 있는 자격 증명을 선택하라는 메시지가 표시됩니다.
* 다음 지역은 검색이 지원되지 않습니다: 중국 지역, GovCloud (미국) 지역, Secret Cloud 및 Top Secret Cloud.


====
.결과
콘솔은 시스템 페이지에 검색된 시스템을 표시합니다. NetApp Console의 워크로드, ONTAP 시스템 관리자 사용 또는 클라우드 공급자의 스토리지 관리 툴 사용 등 여러 가지 방법으로 스토리지 시스템을 관리할 수 있습니다.
