---
sidebar: sidebar 
permalink: fsx-storage/create-cyber-vault.html 
keywords: create cyber vault, volume cyber vault, protect data cyber vault, cyber vault setup 
summary: NetApp 사이버 볼트에 대해 알아보고 랜섬웨어 및 사이버 위협으로부터 데이터를 보호하기 위한 사이버 볼트 아키텍처 구현 방법을 살펴보세요. 
---
= 사이버 금고로 FSx for ONTAP 데이터를 보호하세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사이버 볼트 볼륨은 랜섬웨어 공격 및 기타 사이버 위협으로부터 데이터를 보호하기 위해 데이터 백업 복사본을 저장하는 데 사용되는 격리된 보안 저장 위치입니다. 볼트 생성 과정에서 사이버 볼트 볼륨을 생성하고, 모든 클라이언트 프로토콜을 비활성화하고, 소스 볼륨과 사이버 볼트 볼륨 간의 복제 관계를 설정하고, 사이버 볼트 볼륨에 변경 불가능한 스냅샷을 생성합니다.

.사이버 금고란 무엇입니까?
사이버 볼트는 주요 IT 인프라와 분리된 격리된 환경에 중요 데이터를 저장하는 특정 데이터 보호 기술입니다.

사이버 볼트는 악성코드, 랜섬웨어 또는 내부자 위협 등 메인 네트워크에 영향을 미치는 위협으로부터 안전한 "에어갭(air-gapped)" 방식의, 변경 불가능하고 삭제 불가능한 데이터 저장소입니다. 사이버 볼트는 변경 불가능하고 삭제 불가능한 스냅샷을 통해 구축할 수 있습니다.

기존 방식의 에어갭 백업은 기본 및 보조 저장 매체를 물리적으로 분리하는 공간을 확보하는 것을 포함합니다. 저장 매체를 오프사이트로 이동하거나 연결을 차단함으로써 악의적인 공격자가 데이터에 접근할 수 없도록 합니다. 이는 데이터를 보호하지만 복구 시간이 더 오래 걸릴 수 있습니다.

.FSx for ONTAP 사이버 금고
Amazon FSx for NetApp ONTAP은 사이버 볼트 소스 및 대상으로 지원됩니다.

.구현
Workload Factory는 사이버 볼트 아키텍처 구축을 지원합니다. 사이버 볼트 구현에 대한 관심을 표명하기 위해 NetApp에 문의하시면, NetApp 전문가가 연락을 드려 요구 사항을 논의합니다.

시작하려면 ng-FSx-CyberVault@netapp.com으로 이메일을 보내십시오.

.관련 정보
사이버 금고 및 이러한 아키텍처 설정 방법에 대한 자세한 내용은 link:https://docs.netapp.com/us-en/netapp-solutions-dataops/cyber-vault/ontap-cyber-vault-overview.html["ONTAP 사이버 볼트 문서"^]을(를) 참조하십시오.
