---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: Workload Factory가 Google 계정의 클라우드 리소스를 배포하고 관리하는 데 필요한 권한을 갖도록 Google Cloud NetApp Volumes 자격 증명을 추가하십시오. 
---
= Google Cloud NetApp Volumes 자격 증명을 NetApp Workload Factory에 추가합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory가 클라우드 공급자 계정의 리소스를 배포하고 관리하는 데 필요한 권한을 갖도록 클라우드 공급자 자격 증명을 추가하고 관리하십시오.



[[overview]]
== 개요

NetApp 콘솔의 자격 증명 페이지에서 Google Cloud NetApp Volumes 자격 증명을 추가할 수 있습니다. 콘솔은 안내 설정 지침과 설명서 링크를 제공하므로 필요한 Google Cloud 구성을 완료한 후 돌아와서 자격 증명 추가를 마무리할 수 있습니다.

이 워크플로를 사용하여 Workload Factory가 Google Cloud 환경에서 리소스를 검색, 분석 및 관리하는 데 필요한 권한을 부여하십시오.

자격 증명을 생성하는 과정은 세 단계로 구성됩니다:

* 1단계: Workload Factory에 부여할 권한 수준을 선택합니다.
* 2단계: Google Cloud 서비스 계정을 생성하고 유효성을 검사한 다음 관리할 Google Cloud 프로젝트를 선택합니다.
* 3단계: 자격 증명 이름을 입력하고 자격 증명을 추가합니다.


.시작하기 전에
Google Cloud 계정에 로그인하려면 자격 증명이 필요합니다.

.단계
.  https://console.netapp.com/["NetApp 콘솔"^]에 로그인합니다.
. 메뉴에서 *워크로드* > *관리* > *자격 증명*을 선택하십시오.
. 자격 증명 페이지에서 *자격 증명 추가*를 선택합니다.
. 클라우드 공급자로 *Google Cloud NetApp Volumes*를 선택하십시오.
. Google Cloud NetApp Volumes 자격 증명 추가 페이지에서 *권한 구성* 아래의 각 섹션을 완료하십시오.




[[step-1-create-permission-policies]]
=== 1단계: 권한 정책 생성

.단계
. *권한 정책 만들기*에서 *보기, 계획 및 분석*이 기본적으로 선택되어 있습니다. 이 권한 정책을 사용하면 Google Cloud NetApp Volumes 스토리지 풀을 보고, 시스템 상태를 확인하고, 시스템에 대한 아키텍처 분석을 받고, 비용 절감 방안을 살펴볼 수 있습니다.
. 선택 사항: Workload Factory에서 Google Cloud NetApp Volumes 리소스를 관리하고 구성 문제를 해결하도록 하려면 *운영 및 복구*를 선택하십시오.
. 계속 진행하기 전에 link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["Google Cloud NetApp Volumes 설정"^]에서 설정 지침을 검토하십시오.




[[step-2-create-the-google-cloud-service-account]]
=== 2단계: Google Cloud 서비스 계정 생성

.단계
. *Google Cloud 환경 설정*을 확장합니다.
. 화면에 표시되는 1~5단계를 완료하여 Google Cloud 서비스 계정을 생성하십시오.
. 서비스 계정 이메일 주소를 복사합니다.
. Workload Factory로 돌아가서 이메일 주소를 *GCP 서비스 계정* 필드에 붙여넣고 *자격 증명 확인*을 선택합니다.
. 유효성 검사가 완료되면 *프로젝트* 드롭다운에서 Workload Factory가 관리할 Google Cloud 프로젝트를 선택합니다. 참고: 서비스 계정 자격 증명이 확인될 때까지 프로젝트 목록을 사용할 수 없습니다.




[[step-3-enter-the-credentials-name]]
=== 3단계: 자격 증명 이름을 입력합니다

.단계
. *자격 증명 이름*을 확장합니다.
. *이름* 필드에 영숫자만 사용하여 자격 증명 이름을 입력하십시오. 특수 문자 및 공백은 허용되지 않습니다.
. *추가*를 선택합니다.


.결과
Google Cloud NetApp Volumes 자격 증명이 계정에 추가되어 지원되는 Workload Factory 작업에 사용할 수 있습니다.
