---
sidebar: sidebar 
permalink: gcnv/learn-netapp-volumes.html 
keywords: google cloud netapp volumes, cost, price, features, google cloud netapp volumes features, gcnv, supported regions, google regions, google cloud netapp volumes regions 
summary: Google Cloud NetApp Volumes를 사용하면 기업은 성능 집약적이고 지연 시간에 민감한 핵심 비즈니스 애플리케이션을 클라우드 환경에 맞게 재구성할 필요 없이 Google에서 마이그레이션하고 실행할 수 있습니다. 
---
= Google Cloud NetApp Volumes에 대해 알아보십시오.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Google Cloud NetApp Volumes는 고급 데이터 관리 기능과 뛰어난 확장성을 제공하는 완전 관리형 클라우드 기반 데이터 스토리지 서비스입니다.

NetApp Volumes는 온프레미스 스토리지의 성능과 기능을 유지하면서 배포 시간을 단축하고, 워크로드 및 애플리케이션을 관리하고, 워크로드를 클라우드로 마이그레이션하는 데 도움을 줍니다.



[[features]]
== 기능

* 기업용 애플리케이션을 더 빠르고 효율적으로 실행합니다.
* 클라우드 스토리지 비용을 최대 90%까지 절감합니다.
* 가동 시간, 가용성 및 보안에 대한 요구 사항을 충족합니다.
* NFS, SMB 및 멀티프로토콜 환경을 지원합니다.




[[cost]]
== 비용

Google Cloud NetApp Volumes에서 생성된 볼륨은 NetApp Console을 통하지 않고 서비스 구독에 요금이 부과됩니다.

Google Cloud NetApp Volumes 리전 또는 볼륨을 NetApp Console에서 검색하는 데에는 비용이 발생하지 않습니다.



[[supported-regions]]
== 지원되는 지역

https://cloud.google.com/netapp/volumes/docs/discover/service-levels#supported_regions["지원되는 Google Cloud NetApp Volumes 리전을 확인하십시오."^]



[[getting-help]]
== 도움 받기

기술 지원을 받으려면 Google Cloud 포털을 통해 요청을 제출하십시오. *Storage*에서 Google Cloud 구독과 *Google Cloud NetApp Volumes* 서비스를 선택하십시오. 필요한 정보를 입력하십시오.

Google Cloud NetApp Volumes에 대한 일반적인 질문은 NetApp의 Google Cloud 팀(gcinfo@netapp.com)으로 이메일을 보내주십시오.

클라우드 볼륨과 관련된 기술적인 문제가 발생하면 Google Cloud Console에서 기술 지원 사례를 생성할 수 있습니다. 자세한 내용은 link:https://cloud.google.com/netapp/volumes/docs/support["지원 받기"^]을(를) 참조하십시오.



[[related-links]]
== 관련 링크

* https://cloud.google.com/netapp/volumes/docs/discover/overview["Google Cloud NetApp Volumes 설명서"^]
* https://docs.netapp.com/us-en/data-services-copy-sync/index.html["NetApp Console 복사 및 동기화 설명서"^]

