---
sidebar: sidebar 
permalink: fsx-eda/learn-eda-workloads.html 
keywords: software builders, development, benefits, eda, electronic design automation, perforce integration, ci, cd 
summary: NetApp Workload Factory for EDA에서 Perforce 통합을 사용하는 방법을 알아보십시오. 
---
= Workload Factory for EDA에서 Perforce 통합에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Perforce를 CI/CD 파이프라인과 통합하면 빌드, 테스트 및 배포를 자동화하여 개발 프로세스를 개선하고 더 빠르고 안정적인 소프트웨어 제공이 가능해집니다.

EDA의 지속적 통합 및 지속적 배포(CI/CD)는 소프트웨어 개발자를 위한 신속한 빌드 환경 구축 툴입니다. 이를 통해 개인 개발 환경을 빠르게 설정할 수 있어 시간을 절약하고 개발자를 위한 셀프 서비스를 지원하는 동시에 DevOps 팀이 인프라에 대한 제어력을 유지할 수 있도록 합니다. CI/CD를 사용하면 소프트웨어 개발자는 특수 데이터 스토리지나 개발 인프라에 대한 이해 없이도 작업 공간을 신속하게 생성할 수 있습니다.



[[what-is-cicd]]
== CI/CD란 무엇인가요?

CI/CD를 사용하면 개발자가 소프트웨어의 다양한 버전을 관리하고 상호 작용하는 방식을 간소화할 수 있습니다. Perforce Helix Core와 연동하여 소프트웨어 버전을 즉시 복제하고 개발, QA 및 CI/CD를 위한 작업 공간을 생성할 수 있습니다.

프로젝트를 쉽게 생성하고 소프트웨어 환경과 해당 아티팩트를 나타내는 볼륨을 할당할 수 있습니다. 소프트웨어를 업데이트할 때 볼륨의 스냅샷을 생성하여 그 순간의 소프트웨어 상태를 캡처할 수 있습니다. 재동기화 없이 모든 소프트웨어 버전에 즉시 액세스할 수 있어 시간과 리소스를 절약할 수 있습니다.

NetApp ONTAP의 스냅샷 및 클론 기능을 사용하면 소프트웨어의 다양한 버전에 빠르게 액세스할 수 있으므로 업데이트를 더 신속하게 개발하고 릴리스할 수 있습니다. Workload Factory에 대한 자세한 내용은 link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Workload Factory 개요"^]을(를) 참조하십시오.



[[cicd-features]]
== CI/CD 기능

* 프로젝트를 생성, 편집 및 삭제합니다. link:manage-projects.html["프로젝트 관리"]을(를) 참조하십시오.
* 정의된 소프트웨어 버전의 스냅샷을 생성합니다. link:version-projects.html["프로젝트 버전 관리"]을(를) 참조하십시오.
* (복제본을 기반으로) 워크스페이스를 생성하고 삭제합니다. link:create-workspaces.html["워크스페이스 만들기"]을(를) 참조하십시오.
* 프로젝트에 대한 액세스를 제어하는 액세스 정책을 생성하십시오.
* 각 프로젝트의 용량 사용량을 분석하십시오.
* 각 프로젝트에 대한 클론 크기 제한 및 클론 보존 기간을 제어합니다.
* Perforce 등 버전 관리 시스템과 통합하십시오. link:integrate-perforce.html["Perforce와 통합"]을(를) 참조하십시오.




[[projects-and-workspaces-in-eda]]
== EDA의 프로젝트 및 작업 공간

프로젝트를 생성하고 소프트웨어 환경 및 관련 아티팩트를 나타내는 볼륨을 할당할 수 있습니다. 소프트웨어의 새 버전을 생성할 때마다 볼륨 데이터를 다시 동기화하고 프로젝트 스냅샷을 생성하여 볼륨 상태를 알려진 버전으로 표시해야 합니다. 프로젝트 소스 볼륨은 롤링 업데이트를 받을 수 있으며 여러 버전을 표시하기 위해 여러 스냅샷을 가질 수 있습니다. 각 스냅샷은 개발자, QA 또는 빌드 프로세스에서 사용할 수 있는 전용 또는 공유 편집 가능 저장소인 인스턴트 클론으로 즉시 사용할 수 있습니다. 특정 소프트웨어 버전의 컨텍스트에서 클론은 워크스페이스입니다.



[[automation-with-workload-factory-codebox]]
== Workload Factory Codebox를 이용한 자동화

Workload Factory는 _Codebox_를 통해 내장 자동화 기능을 제공합니다. Codebox는 다음과 같은 자동화 이점을 제공합니다.

* *코드 스니펫 생성*: 코드형 인프라(IaC) 스니펫은 리소스 생성 중에 생성되므로 기존 오케스트레이션 워크플로와 원활하게 통합할 수 있습니다.
* *인프라스트럭처 코드 코파일럿*: Codebox는 개발자와 DevOps가 Workload Factory에서 지원하는 모든 작업을 실행하는 코드를 생성할 수 있도록 도와주는 인프라스트럭처 코드(IaC) 코파일럿입니다.
* *코드 뷰어 및 자동화 카탈로그*: Codebox는 자동화의 빠른 분석을 위한 코드 뷰어와 향후 빠른 재사용을 위한 자동화 카탈로그를 제공합니다.




[[cost]]
== 비용

Workload Factory의 CI/CD 기능을 사용하는 데에는 비용이 들지 않습니다.



[[licensing]]
== 라이센싱

Workload Factory의 CI/CD 기능을 사용하기 위해 NetApp으로부터 특별한 라이선스가 필요하지 않습니다.



[[regions]]
== 지역

EDA는 FSx for ONTAP이 지원되는 모든 상업 지역에서 지원됩니다. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 Amazon 리전을 확인하십시오."^]

다음 AWS 리전은 지원되지 않습니다:

* 중국 지역
* Secret Cloud
* 최고 기밀 클라우드




[[getting-help]]
== 도움 받기

Amazon FSx for NetApp ONTAP은 AWS 자체 솔루션입니다. 지원을 받으려면 AWS Management Console의 지원 센터를 사용하여 케이스를 개설하십시오. "FSx for ONTAP" 및 범주를 선택한 다음 필요한 정보를 제공하십시오.

Workload Factory 또는 Workload Factory 애플리케이션 및 서비스에 대한 일반적인 질문은 link:../get-help.html["Workload Factory용 EDA 관련 도움을 받으세요"]을(를) 참조하십시오.
