---
sidebar: sidebar 
permalink: fsx-databases/learn-about-databases.html 
keywords: Databases, FSx for ONTAP, Workload Factory 
summary: NetApp Workload Factory for Databases는 최적화, 자동 씬 클로닝, 모니터링 및 문제 해결 기능을 위한 모범 사례가 내장된 엔드투엔드 데이터베이스 배포 및 유지 관리 서비스입니다. 
---
= NetApp Workload Factory for Databases에 대해 알아보십시오.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory for Databases는 최적화, 자동 씬 클로닝, 모니터링 및 문제 해결 기능을 위한 모범 사례가 내장된 엔드투엔드 데이터베이스 배포 및 유지 관리 서비스입니다.



[[what-is-netapp-workload-factory-for-databases]]
== NetApp Workload Factory for Databases란 무엇입니까?

NetApp Workload Factory for Databases는 Microsoft SQL Server, PostgreSQL 및 Oracle 데이터를 Amazon FSx for NetApp ONTAP(FSx for ONTAP) 배포 환경으로 검색, 평가, 계획, 프로비저닝 및 마이그레이션합니다. 이러한 배포 환경은 업계 모범 사례를 준수하면서 성능 및 비용 기대치를 충족하도록 최적화됩니다. NetApp Workload Factory for Databases는 FSx for ONTAP에서 데이터베이스를 지속적으로 최적화하고 관리합니다.

link:../setup/learn-about-workload-factory.html["Workload Factory에 대해 자세히 알아보십시오"].



[[workload-factory-benefits-for-self-managed-databases]]
== 자체 관리형 데이터베이스를 위한 Workload Factory의 이점

Workload Factory는 자체 관리형 데이터베이스를 위한 모범 사례와 자동화 기능을 제공합니다.



[[best-practices]]
=== 모범 사례

* EC2 인스턴스의 SQL 서버 배포를 위한 AWS 클라우드, Microsoft Windows 및 SQL 서버, 그리고 NetApp ONTAP의 통합 지식.
* 총 소유 비용 최적화 배포.
* AWS, Microsoft 및 ONTAP의 모범 사례를 따르는 엔드투엔드 배포 자동화.
* _빠른 생성_ 배포 모드는 수동 구성에 따른 잠재적인 문제를 방지하는 데 도움이 됩니다.




[[automation-with-workload-factory-codebox]]
=== Workload Factory Codebox를 이용한 자동화

Workload Factory는 _Codebox_를 통해 내장 자동화 기능을 제공합니다. Codebox는 다음과 같은 자동화 이점을 제공합니다.

* *코드 스니펫 생성*: Workload Factory는 리소스 생성 중에 IaC(Infrastructure-as-Code) 스니펫을 생성하여 기존 오케스트레이션 워크플로와의 원활한 통합을 지원합니다.
* *인프라스트럭처 코드 코파일럿*: Codebox는 개발자와 DevOps가 Workload Factory에서 지원하는 모든 작업을 실행하는 코드를 생성할 수 있도록 도와주는 인프라스트럭처 코드(IaC) 코파일럿입니다.
* *코드 뷰어 및 자동화 카탈로그*: Codebox는 자동화의 빠른 분석을 위한 코드 뷰어와 향후 빠른 재사용을 위한 자동화 카탈로그를 제공합니다.




[[workload-factory-for-databases-features]]
=== Workload Factory for Databases 기능

데이터베이스용 Workload Factory는 다음과 같은 기능을 제공합니다:

* *비용 추정*: 기존 Microsoft SQL Server 및 Oracle 배포 환경(Elastic Block Store, FSx for Windows File Server 및 온프레미스 포함)과 FSx for ONTAP을 비교했을 때 스토리지, 컴퓨팅, SQL 라이선스, 스냅샷 및 클론 관련 항목별 비용을 추정하고 자세히 보여주는 비용 절감 계산기를 사용하여 잠재적인 비용 절감 효과를 평가해 보세요.
* *간편하고 빠른 배포*: NetApp, Microsoft 및 Amazon의 모범 사례가 내장되어 있어 호스트, 데이터베이스 및 샌드박스 프로비저닝을 간소화하고 효율화하여 AWS에서 Microsoft SQL Server 및 PostgreSQL 인스턴스를 수동으로 구성하는 복잡성을 제거합니다.
+
** Workload Factory 콘솔에서 _Quick_ 또는 _Advanced_ 생성 모드를 사용하여 배포하거나, Codebox를 통해 AWS CloudFormation 템플릿을 생성, 재사용 및 사용자 지정하여 여러 환경에 걸쳐 향후 배포에 활용할 수 있습니다.
** 스토리지 구성 및 샌드박스 클론을 사용하여 온디맨드 격리 데이터베이스를 생성하여 테스트, 통합, 진단 및 교육에 사용할 수 있으며 운영 데이터에 영향을 주지 않습니다.


* *Well-architected 평가 기능*: Microsoft SQL Server 및 Oracle 환경을 지속적으로 스캔하여 AWS 모범 사례를 기반으로 운영 효율성, 보안, 안정성, 성능 효율성 및 비용 최적화를 달성하는 데 도움이 되는 통찰력, 기회 및 권장 사항에 대한 종합 보고서를 제공합니다.
* *오류 분석*: AI 분석기를 사용하여 로그 오류를 분석하고 문제를 해결하여 자세한 오류 메시지, 문제 해결 단계 및 문제 해결을 위한 권장 사항을 확인하십시오.
* *중앙 집중식 관리*: 한 곳에서 Amazon FSx for NetApp ONTAP의 Microsoft SQL Server, Oracle 및 PostgreSQL 리소스를 관리하세요. Workload Factory에서 연결된 인프라, AWS 계정, 자격 증명, 연결된 Amazon FSx for NetApp ONTAP 파일 시스템, NFS 볼륨 및 iSCSI LUN을 포함한 스토리지 사용량, 보호 상태, 성능, 아키텍처 우수성 상태 및 오류 분석을 확인할 수 있습니다.




[[benefits-of-amazon-fsx-for-ontap-for-self-managed-databases]]
== 자체 관리형 데이터베이스를 위한 Amazon FSx for ONTAP의 이점

* *내구성, 가용성 및 신뢰성*: FSx for ONTAP은 단일 및 다중 가용성 영역 배포를 지원하는 고가용성, 애플리케이션 인식 스냅샷, 복제를 사용한 향상된 재해 복구, 효율적인 백업 등 FSx for ONTAP에서 호스팅되는 자체 관리형 데이터베이스의 내구성과 가용성을 향상시키는 다양한 기능을 제공합니다.
* *성능 및 확장성*: FSx for ONTAP은 높은 처리량, 낮은 지연 시간, 고속 네트워크 연결을 통한 성능 최적화와 워크로드에 필요한 총 성능을 확장하기 위한 여러 파일 시스템을 통한 확장성을 제공합니다.
* *데이터 관리 및 효율성*: FSx for ONTAP은 공간 효율적인 씬 클론, 씬 프로비저닝, 압축 및 중복 제거, 자주 액세스하지 않는 데이터를 용량 풀로 계층화하는 기능 등 데이터 관리 및 효율성을 향상시키는 다양한 기능을 제공합니다.


link:../fsx-storage/learn-fsx-ontap.html["Workload Factory용 FSx for ONTAP에 대해 알아보십시오."^].



[[tools-to-use-netapp-workload-factory]]
== NetApp Workload Factory 사용 툴

NetApp Workload Factory를 다음 툴과 함께 사용할 수 있습니다:

* *Workload Factory 콘솔*: Workload Factory 콘솔은 애플리케이션 및 프로젝트에 대한 시각적이고 전체적인 보기를 제공합니다.
* *NetApp Console*: NetApp Console은 하이브리드 인터페이스 환경을 제공하므로 Workload Factory를 다른 NetApp 데이터 서비스와 함께 사용할 수 있습니다.
* *Ask me*: Workload Factory 콘솔을 벗어나지 않고도 Ask me AI 도우미를 사용하여 질문하고 Workload Factory에 대해 자세히 알아볼 수 있습니다. Workload Factory 도움말 메뉴에서 Ask me에 액세스할 수 있습니다.
* *CloudShell CLI*: Workload Factory에는 단일 브라우저 기반 CLI에서 계정 전반의 AWS 및 NetApp 환경을 관리하고 운영할 수 있는 CloudShell CLI가 포함되어 있습니다. Workload Factory 콘솔의 상단 표시줄에서 CloudShell에 액세스합니다.
* *REST API*: Workload Factory REST API를 사용하여 FSx for ONTAP 파일 시스템 및 기타 AWS 리소스를 배포하고 관리할 수 있습니다.
* *CloudFormation*: AWS CloudFormation 코드를 사용하여 Workload Factory 콘솔에서 정의한 작업을 수행함으로써 AWS 계정의 CloudFormation 스택에서 AWS 및 타사 리소스를 모델링, 프로비저닝 및 관리할 수 있습니다.
* *NetApp Terraform 공급자*: Workload Factory 콘솔에서 생성된 인프라 워크플로를 구축하고 관리하기 위해 Terraform을 사용합니다.




[[supported-configurations]]
== 지원되는 구성

AWS, NetApp ONTAP, Microsoft SQL Server, Oracle 및 PostgreSQL의 모범 사례를 준수하여 Workload Factory를 다음 데이터베이스 엔진, 버전, 운영 체제 및 배포 모델과 함께 사용할 수 있습니다.

[cols="1,1,1,1"]
|===
| 엔진 | 버전 | 운영 체제 | 배포 모델 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2025 | Windows Server 2025 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2017 | 모든 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2016, 2017,2019, 2022 | 모든 | FCI, 독립형 


| Microsoft SQL Server | SQL Server 2016, 2017,2019, 2022 | 모든 | Always On 가용성 그룹 


| Oracle | 19c | RHEL, SuSe Linux | 독립형(단일/다중 테넌트) 


| Oracle | 21c | RHEL, SuSe Linux | 독립형(단일/다중 테넌트) 


| Oracle | 19c | RHEL, SuSe Linux | 독립형(단일/다중 테넌트) 


| Oracle | 21c | RHEL, SuSe Linux | 독립형(단일/다중 테넌트) 


| Oracle | 19c | RHEL, SuSe Linux | ASM을 지원하는 독립형(단일/다중 테넌트) 


| Oracle | 21c | RHEL, SuSe Linux | ASM을 지원하는 독립형(단일/다중 테넌트) 


| Oracle | 19c, 21c | RHEL, SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | Amazon Linux 2023 AMI | HA, 독립형 인스턴스 


| PostgreSQL | PostgreSQL 16 | Amazon Linux 2023 AMI | HA, 독립형 인스턴스 
|===


[[integrated-aws-services]]
== 통합 AWS 서비스

데이터베이스에는 다음과 같은 통합 AWS 서비스가 포함됩니다.

* CloudFormation
* Simple Notification Service
* CloudWatch
* Systems Manager
* Secrets Manager




[[regions]]
== 지역

데이터베이스는 FSx for ONTAP이 지원되는 모든 상업 지역에서 지원됩니다. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["지원되는 Amazon 리전을 확인하십시오."^]

다음 AWS 리전은 지원되지 않습니다:

* 중국 지역
* Secret Cloud
* 최고 기밀 클라우드




[[getting-help]]
== 도움 받기

Amazon FSx for NetApp ONTAP은 AWS 자체 솔루션입니다. FSx for ONTAP 파일 시스템, 인프라 또는 이 서비스를 사용하는 솔루션과 관련된 질문이나 기술 지원 문제가 있는 경우 AWS Management Console의 Support Center를 사용하여 AWS에 지원 케이스를 개설하십시오. “FSx for ONTAP” 서비스와 적절한 범주를 선택하십시오. AWS 지원 케이스를 생성하는 데 필요한 나머지 정보를 제공하십시오.

Workload Factory 또는 Workload Factory 애플리케이션 및 서비스에 대한 일반적인 질문은 link:../get-help.html["NetApp Workload Factory for Databases 관련 도움말을 받으세요."]을(를) 참조하십시오.
