---
sidebar: sidebar 
permalink: admin/well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory는 워크로드 구성을 스캔하여 안정성, 보안, 운영 우수성, 비용 최적화 및 성능 효율성을 평가하고, 운영 우수성을 달성하는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= NetApp Workload Factory가 잘 설계된 워크로드를 지원하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Workload Factory는 클라우드 공급업체의 Well-Architected Framework에 맞춰 안정적이고 안전하며 효율적이고 비용 효율적인 워크로드 구성을 유지 및 운영할 수 있도록 지원합니다. Workload Factory는 워크로드에 대한 일일 분석, 권장 사항 및 자동 수정 기능을 제공하여 건전한 워크로드 운영을 촉진합니다. 이러한 프로세스를 자동화함으로써 Workload Factory는 인적 오류를 최소화하고 워크로드 관리의 일관성을 보장합니다.



[[how-it-works]]
== 작동 방식

Workload Factory는 지원되는 클라우드 스토리지 시스템 배포 환경에서 실행되는 워크로드를 매일 분석합니다. 이 분석을 통해 아키텍처가 잘 설계된 상태, 인사이트 및 권장 사항을 제공합니다.

일일 분석이 완료되면 배포의 Well-architected 대시보드에 구성 상태가 "최적화됨" 또는 "최적화되지 않음"으로 표시됩니다. 구성 문제는 범주별로 분류되어 있으며, 구성 문제 목록과 권장 사항도 확인할 수 있습니다. 구성 문제에 대한 권장 사항을 검토할 수 있습니다. 일부 문제는 Workload Factory에서 자동으로 수정되지만, 다른 문제는 수동 수정이 필요합니다. 이 경우 Workload Factory는 권장 변경 사항을 구현하는 데 도움이 되는 자세한 지침을 제공합니다.

사용 환경에 적용되지 않는 구성에 대한 분석은 제외할 수 있습니다. 이렇게 하면 불필요한 알림과 부정확한 최적화 결과를 방지할 수 있습니다.

또한 일반 언어로 사용자 지정 규칙을 만들어 조직 표준 및 NetApp 모범 사례에 따라 환경의 유효성을 검사할 수 있습니다. 모의 실행을 통해 규칙을 테스트한 다음, 모든 환경에서 실행되도록 예약할 수 있습니다. link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["사용자 지정 규칙에 대해 자세히 알아보기"^].



[[why-it-matters]]
== 중요한 이유

Workload Factory는 지속적인 평가와 권장 사항 및 문제 해결을 결합하여 대규모 스토리지, 데이터베이스 및 VMware 환경에 최적의 솔루션을 적용합니다. NetApp Console에서 자동으로 적용되는 수정 사항은 인적 오류를 줄이고, 일관된 관리를 보장하며, 워크로드 인프라 전반의 성능과 안정성을 유지합니다.



[[get-started-with-workload-factory-to-detect-and-fix-workload-misconfigurations]]
== Workload Factory를 사용하여 워크로드 구성 오류를 감지하고 수정해 보세요

Workload Factory를 시작하려면 가입하고 자격 증명을 추가한 다음 연결을 설정하여 AWS 리소스를 관리하고 Amazon FSx for NetApp ONTAP를 사용하여 워크로드를 최적화하십시오.

link:../fsx-storage/quick-start-fsx.html["빠른 시작"]

.관련 정보
다음 페이지에서는 다양한 NetApp 스토리지 솔루션에 걸쳐 잘 설계된 구성을 구현하는 방법에 대한 지침을 제공합니다:

* link:../fsx-storage/improve-configurations.html["잘 설계된 FSx for ONTAP 파일 시스템 구현"]
* link:../fsx-databases/optimize-configurations.html["잘 설계된 데이터베이스 구성을 구현하십시오"]
* link:../fsx-vmware/view-evs-well-architected.html["잘 설계된 EVS 구성 구현"]
* link:../gcnv/improve-configurations.html["잘 설계된 NetApp 볼륨 구성을 구현하십시오."]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-improve-configurations-cvo.html["Microsoft Azure에서 잘 설계된 Cloud Volumes ONTAP 시스템 구성을 구현하세요"^]

