---
sidebar: sidebar 
permalink: setup/learn-about-permissions.html 
keywords: permissions, actions 
summary: NetApp Workload Factory 기능 및 서비스를 사용하려면 Workload Factory가 클라우드 환경에서 작업을 수행할 수 있도록 권한을 제공해야 합니다. 
---
= NetApp Workload Factory에 대한 권한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory 기능 및 서비스를 사용하려면 Workload Factory가 클라우드 환경에서 작업을 수행할 수 있도록 권한을 제공해야 합니다.



[[why-use-permissions]]
== 권한을 사용하는 이유는 무엇일까요?

권한을 부여하면 Workload Factory는 클라우드 공급자 계정 내의 리소스 및 프로세스를 관리할 수 있는 권한이 포함된 정책을 인스턴스에 연결합니다. 이를 통해 Workload Factory는 스토리지 환경 검색부터 스토리지 관리의 볼륨 등 클라우드 리소스 배포에 이르기까지 다양한 작업을 수행할 수 있습니다.

예를 들어 FSx for ONTAP 데이터베이스 워크로드의 경우, Workload Factory에 필요한 권한이 부여되면 지정된 계정 및 리전의 모든 EC2 인스턴스를 스캔하고 모든 Windows 기반 머신을 필터링합니다. 호스트에 AWS Systems Manager (SSM) 에이전트가 설치되어 실행 중이고 System Manager 네트워킹이 올바르게 구성된 경우 Workload Factory는 Windows 머신에 액세스하여 SQL Server 소프트웨어가 설치되어 있는지 확인할 수 있습니다.



[[how-permissions-are-used]]
== 권한 사용 방법

Workload Factory는 특정 작업을 수행하기 위해 권한을 사용합니다. 권한은 권한 정책 세트로 묶입니다. 권한 정책은 link:../admin/codebox-automation.html["Codebox"]에 표시되며 복사 가능한 JSON입니다. 각 클라우드 공급자는 해당 클라우드 환경의 특정 요구사항 및 기능에 맞게 조정된 자체 권한 정책 세트를 가지고 있습니다. 이 문서에서는 각 클라우드 공급자에 대한 권한 참조를 제공합니다.



[[permission-references-by-cloud-provider]]
=== 클라우드 제공업체별 권한 참조

클라우드 제공업체의 권한 요구 사항에 대해 알아보려면 다음 페이지를 참조하십시오:

* link:../fsx-storage/permissions-reference-fsx.html["Amazon FSx for NetApp ONTAP"]
* link:../oci/permissions-oci.html["OCI NetApp 스토리지 서비스"]

