---
sidebar: sidebar 
permalink: setup/links-overview.html 
keywords: links, accounts, connectivity, 
summary: Workload Factory 링크는 Workload Factory 계정과 하나 이상의 클라우드 스토리지 시스템 간의 신뢰 관계 및 연결성을 구축합니다. 
---
= NetApp Workload Factory 링크에 대해 알아보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory 링크는 Workload Factory 계정과 하나 이상의 클라우드 스토리지 시스템 간의 신뢰 관계 및 연결을 생성합니다. 이를 통해 클라우드 공급자 API를 통해 사용할 수 없는 특정 스토리지 시스템 기능을 ONTAP REST API 호출을 통해 직접 모니터링하고 관리할 수 있습니다.

Workload Factory를 시작하는 데에는 링크가 필요하지 않지만, 경우에 따라 Workload Factory의 모든 기능과 워크로드 기능을 사용하려면 링크를 생성해야 합니다.



[[why-links-are-beneficial]]
== 링크가 유익한 이유

링크는 Workload Factory가 클라우드 공급자의 API를 통해 기본적으로 제공되지 않는 작업을 수행할 수 있도록 해주기 때문에 유용합니다. 링크를 통해 고급 ONTAP 기능과 자동화를 활용할 수 있으며, 이는 클라우드 스토리지 시스템 관리를 향상시켜 줍니다.

링크 사용의 이점은 다음과 같습니다.

* 이 연결을 통해 NetApp Console은 ONTAP 명령을 클라우드 스토리지 시스템으로 직접 전송할 수 있으며, 클라우드 공급자가 기본적으로 제공하는 기능 이상의 고급 ONTAP 기능을 제공합니다.
* 링크는 원격 서버리스 함수를 활용하여 이벤트에 대한 응답으로 코드를 실행합니다. 이러한 서버리스 접근 방식은 VPC 내에서 실행되는 인스턴스에 대한 의존성을 제거합니다.




[[how-links-work]]
== 링크 작동 방식

링크는 AWS Lambda 및 Oracle Cloud Infrastructure Functions 등 원격 서버리스 컴퓨팅 서비스를 활용합니다. 이러한 서비스는 이벤트에 응답하여 코드를 실행하고 해당 코드에 필요한 컴퓨팅 리소스를 자동으로 관리합니다. 사용자가 생성하는 링크는 NetApp 계정의 일부이며 해당 클라우드 공급자 계정과 연결됩니다.

링크를 생성한 후에는 하나 또는 여러 개의 클라우드 스토리지 시스템과 연결할 수 있습니다. 각 클라우드 스토리지 시스템은 동일한 NetApp 계정 내에서 하나의 링크에만 연결될 수 있습니다. NetApp 계정이 여러 개인 경우, 하나의 클라우드 스토리지 시스템을 다른 NetApp 계정의 추가 링크와 연결할 수 있습니다.

클라우드 스토리지 시스템에 대한 링크를 NetApp Console의 링크 페이지에서 생성하고 연결합니다.

Workload Factory 자격 증명 서비스 또는 클라우드 공급자의 자격 증명 서비스에 저장된 자격 증명을 사용하여 링크를 인증할 수 있습니다. Workload Factory는 인증 모드 변경을 지원하지 않습니다.



[[costs]]
== 비용

클라우드 제공업체의 서버리스 컴퓨팅 서비스가 수행하는 각 트랜잭션에는 요금이 부과됩니다. 해당 서비스는 두 시스템 간의 프록시 역할을 하므로, 파일 시스템의 ONTAP REST API에 요청을 보낼 때와 Workload Factory로 응답을 다시 보낼 때 요금이 발생합니다.

* link:https://aws.amazon.com/lambda/pricing/["AWS Lambda 사용과 관련된 비용에 대해 자세히 알아보십시오."^]
* link:https://www.oracle.com/cloud/cloud-native/functions/["Oracle Cloud Infrastructure Functions 사용과 관련된 비용에 대해 자세히 알아보세요."^]




[[when-a-link-is-required]]
== 링크가 필요한 경우

Workload Factory는 일부 정보를 표시하고 일부 작업을 수행하기 위해 링크가 필요합니다. 링크가 필요한 작업을 수행하려고 할 때 클라우드 스토리지 시스템에 링크를 연결하지 않은 경우, Workload Factory는 해당 작업에 링크가 필요하다고 알려줍니다.

링크가 필요한 기능은 다음과 같습니다.

* 사전 예방적 유지 관리, 신뢰성 및 비용 대비 성능 최적화를 위한 클라우드 스토리지 시스템 구성의 잘 설계된 상태
* ONTAP EMS 이벤트 모니터링 및 알림
* NetApp 자율형 랜섬웨어 보호(ARP/AI)
* 클라우드 스토리지 시스템 전반에 걸친 향상된 통합 용량 관찰 기능
* 볼륨 및 스토리지 VM 데이터 복제, 관리 및 모니터링
* SMB/CIFS 공유 및 NFS 엑스포트 정책 프로비저닝 및 관리
* 클라우드 스토리지 시스템의 iSCSI 볼륨 관리
* 사용자 지정 보호 SLA를 위한 스냅샷 정책 생성 및 관리
* 자동 용량 관리를 위한 Inode 관리 기능 향상
* 탄력적 확장을 위한 볼륨 자동 증가
* 즉각적인 인플레이스 데이터 클로닝을 위한 클론 생성 및 관리
* 시스템 버전 등 클라우드 스토리지 시스템에서 직접 추가 메트릭 표시
* 스토리지 VM 및 클러스터 LIF의 역할, 엔드포인트, 노드, IP 주소 및 상태를 포함한 세부 정보 표시
* 지연 이벤트에 대한 구성 요소 분석




[[related-information]]
== 관련 정보

다음 항목에 대한 링크를 만들고 연결하는 방법을 알아보세요.

* link:../fsx-storage/create-link.html["Amazon FSx for NetApp ONTAP"]
* link:../oci/create-link.html["OCI NetApp 스토리지 서비스"]

